name: Goorm Project deploy to EKS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: default # default is latest stable
        id: install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR

        run: |
          docker build -t goorm-final .
          docker tag goorm-final:latest public.ecr.aws/k7b3l8g3/goorm-final:latest
          docker push public.ecr.aws/k7b3l8g3/goorm-final:latest

      - name: Update kube config
        run: aws eks update-kubeconfig --name goorm-final-1lNzeXRJ

      - name: Deploy to EKS
        run: |
          kubectl apply -k .